// Generated by CoffeeScript 2.3.2
(function() {
  var Phrase, TranslatedPhrase, frase, phrase, reverseIt;

  reverseIt = function(string) {
    return Array.from(string).reverse().join('');
  };

  Phrase = class Phrase {
    constructor(content) {
      this.content = content;
    }

    processor(string) {
      return string.toLowerCase();
    }

    processedContent() {
      console.log("At Phrase");
      return this.processor(this.content);
    }

    palindrome() {
      return this.processedContent() === reverseIt(this.processedContent());
    }

    louder() {
      return this.content.toUpperCase();
    }

  };

  TranslatedPhrase = class TranslatedPhrase extends Phrase {
    constructor(content, translation) {
      super();
      this.content = content;
      this.translation = translation;
    }

    processedContent() {
      console.log("At TranslatedPhrase");
      return this.processor(this.translation);
    }

  };

  phrase = new Phrase("recognize");

  console.log(phrase.palindrome());

  frase = new TranslatedPhrase("recognize", "rer");

  console.log(frase.palindrome());

  //phrase = new Phrase "Racecar"

//console.log phrase.palindrome()
//console.log phrase.louder()

}).call(this);

//# sourceMappingURL=palindrome.js.map
