// Generated by CoffeeScript 2.3.2
(function() {
  var Phrase, TranslatedPhrase, frase, phrase, reverseIt;


  reverseIt = function(string) {
    return Array.from(string).reverse().join('');
  };

  Phrase = class Phrase {
    constructor(content) {
      this.content = content;
    }

    processor(string) {
      return this.letters().toLowerCase();
    }

    processedContent() {
      return this.processor(this.content);
    }

    palindrome() {
      return this.processedContent() === reverseIt(this.processedContent());
    }

    louder() {
      return this.content.toUpperCase();
    }

    letters() {
      return (this.content.match(/[a-z]/gi) || []).join("");
    }
    
  };

  TranslatedPhrase = class TranslatedPhrase extends Phrase {
    constructor(content, translation) {
      super();
      this.content = content;
      this.translation = translation;
    }

    processedContent() {
      return this.processor(this.translation);
    }

  };

  phrase = new Phrase("recognize");

  module.exports = Phrase
    
  frase = new TranslatedPhrase("recognize", "rer");


  //phrase = new Phrase "Racecar"

//console.log phrase.palindrome()
//console.log phrase.louder()

}).call(this);

//# sourceMappingURL=palindrome.js.map
